# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ragify_pb2 as ragify__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ragify_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorStoreServiceStub:
    """Vector store / collection management (wraps src.ragify.retrieval).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/ragify.v1.VectorStoreService/CreateCollection',
                request_serializer=ragify__pb2.WorkspaceRequest.SerializeToString,
                response_deserializer=ragify__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/ragify.v1.VectorStoreService/DeleteCollection',
                request_serializer=ragify__pb2.WorkspaceRequest.SerializeToString,
                response_deserializer=ragify__pb2.Empty.FromString,
                _registered_method=True)
        self.InsertDocuments = channel.unary_unary(
                '/ragify.v1.VectorStoreService/InsertDocuments',
                request_serializer=ragify__pb2.InsertDocumentsRequest.SerializeToString,
                response_deserializer=ragify__pb2.InsertDocumentsResponse.FromString,
                _registered_method=True)


class VectorStoreServiceServicer:
    """Vector store / collection management (wraps src.ragify.retrieval).
    """

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=ragify__pb2.WorkspaceRequest.FromString,
                    response_serializer=ragify__pb2.Empty.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=ragify__pb2.WorkspaceRequest.FromString,
                    response_serializer=ragify__pb2.Empty.SerializeToString,
            ),
            'InsertDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertDocuments,
                    request_deserializer=ragify__pb2.InsertDocumentsRequest.FromString,
                    response_serializer=ragify__pb2.InsertDocumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ragify.v1.VectorStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ragify.v1.VectorStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorStoreService:
    """Vector store / collection management (wraps src.ragify.retrieval).
    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.VectorStoreService/CreateCollection',
            ragify__pb2.WorkspaceRequest.SerializeToString,
            ragify__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.VectorStoreService/DeleteCollection',
            ragify__pb2.WorkspaceRequest.SerializeToString,
            ragify__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.VectorStoreService/InsertDocuments',
            ragify__pb2.InsertDocumentsRequest.SerializeToString,
            ragify__pb2.InsertDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IngestionServiceStub:
    """Ingestion services (wraps src.ragify.ingestion).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSection = channel.unary_unary(
                '/ragify.v1.IngestionService/ProcessSection',
                request_serializer=ragify__pb2.ProcessSectionRequest.SerializeToString,
                response_deserializer=ragify__pb2.ProcessSectionResponse.FromString,
                _registered_method=True)
        self.ConvertToMarkdown = channel.unary_unary(
                '/ragify.v1.IngestionService/ConvertToMarkdown',
                request_serializer=ragify__pb2.ConvertToMarkdownRequest.SerializeToString,
                response_deserializer=ragify__pb2.ConvertToMarkdownResponse.FromString,
                _registered_method=True)
        self.ProcessDocument = channel.unary_unary(
                '/ragify.v1.IngestionService/ProcessDocument',
                request_serializer=ragify__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=ragify__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.IngestPdf = channel.unary_unary(
                '/ragify.v1.IngestionService/IngestPdf',
                request_serializer=ragify__pb2.IngestPdfRequest.SerializeToString,
                response_deserializer=ragify__pb2.IngestPdfResponse.FromString,
                _registered_method=True)


class IngestionServiceServicer:
    """Ingestion services (wraps src.ragify.ingestion).
    """

    def ProcessSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertToMarkdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestPdf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSection': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSection,
                    request_deserializer=ragify__pb2.ProcessSectionRequest.FromString,
                    response_serializer=ragify__pb2.ProcessSectionResponse.SerializeToString,
            ),
            'ConvertToMarkdown': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertToMarkdown,
                    request_deserializer=ragify__pb2.ConvertToMarkdownRequest.FromString,
                    response_serializer=ragify__pb2.ConvertToMarkdownResponse.SerializeToString,
            ),
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=ragify__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=ragify__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'IngestPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestPdf,
                    request_deserializer=ragify__pb2.IngestPdfRequest.FromString,
                    response_serializer=ragify__pb2.IngestPdfResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ragify.v1.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ragify.v1.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService:
    """Ingestion services (wraps src.ragify.ingestion).
    """

    @staticmethod
    def ProcessSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.IngestionService/ProcessSection',
            ragify__pb2.ProcessSectionRequest.SerializeToString,
            ragify__pb2.ProcessSectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertToMarkdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.IngestionService/ConvertToMarkdown',
            ragify__pb2.ConvertToMarkdownRequest.SerializeToString,
            ragify__pb2.ConvertToMarkdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.IngestionService/ProcessDocument',
            ragify__pb2.ProcessDocumentRequest.SerializeToString,
            ragify__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.IngestionService/IngestPdf',
            ragify__pb2.IngestPdfRequest.SerializeToString,
            ragify__pb2.IngestPdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RagServiceStub:
    """RAG query execution (wraps src.ragify.generation graph).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/ragify.v1.RagService/Query',
                request_serializer=ragify__pb2.QueryRequest.SerializeToString,
                response_deserializer=ragify__pb2.QueryResponse.FromString,
                _registered_method=True)


class RagServiceServicer:
    """RAG query execution (wraps src.ragify.generation graph).
    """

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=ragify__pb2.QueryRequest.FromString,
                    response_serializer=ragify__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ragify.v1.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ragify.v1.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService:
    """RAG query execution (wraps src.ragify.generation graph).
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragify.v1.RagService/Query',
            ragify__pb2.QueryRequest.SerializeToString,
            ragify__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
